### ISSUE TITLE
CLI MVP

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/cli#1]
## Is your feature request related to a problem? Please describe.

Nevermined has a CLI based in the NVM Java SDK. It's not the latest functionality and we lack of a CLI up to date and able to be used in environments without the Java VM. This issue describes the essential functionalities a CLI MVP needs to have in order to replace the existing Java CLI for a CLI based in Typescript.

## Describe the solution you'd like

The CLI needs to have the following functionalities:

- [x]  https://github.com/nevermined-io/cli/issues/4
  - Publish dataset
  - Publish algorithm
  - Publish workflow
  - Publish asset importing a metadata JSON file
  - Resolve a DID
  - Search asset
  - Order an asset
  - Download a previously ordered asset
  - Download my own asset (only asset owners)

- [x] Agreements
  - Lists all agreements for given DID
  - Shows details about an agreement

- [x] NFTs (#8 )
  - Retrieves information about an NFT
  - Creates an NFT
  - Mints an NFT
  - Orders an NFT by paying for it to the escrow
  - Transfers the NFT to the buyer and the funds from the escrow to the seller
  - Downloads the data of an NFT

- [x] Accounts
  - List all accounts
  - Get the balance of an account
  - Create a new account
  - Import an account 
  - Transfer tokens between accounts

- [x] Provenance. 
  - Registering of the W3C Provenance methods (usage, derivation, association, delegation, ..)
  - Inspect, fetch the on-chain information about a provenance id
  - History, get the provenance history for a specific asset given a DID

- [X] Shows the NVM and CLI configuration (#9)

- [x] #12 

### Further Phases

* Manage computation (Nice to Have)
  - Execute a compute service given a DID
  - Fetch the logs of a compute job
  - Get the current status of a compute job

## Additional context

Use for reference the existing CLI implementation `java-cli` and the `vitadao-cli`

**Comment by H34D** [comment]
command structure should be similar to: https://github.com/nevermined-io/java-cli/blob/master/docs/UsefulCommands.md
