### ISSUE TITLE
Artifacts downloading fails if destination is specified

### ISSUE THREAD

**Issue by ialberquilla** [nevermined-io/cli#68]
## Describe the bug
Artifacts downloading fails if destination is specified

 ncli utils download-artifacts 2.0.5 --networkId 80001 --tag public --destination /tmp/artifacts      
Checking available artifacts from the repository: https://artifacts-nevermined-rocks.s3.amazonaws.com
Command failed: destination.length is not a function

##  To Reproduce
1. Download artifacts specifying --destination flag 
2.  ` ncli utils download-artifacts 2.0.5 --networkId 80001 --tag public --destination /tmp/artifacts`

## Expected behavior
Download artifacts

**Comment by aaitor** [comment]
fixed here: https://github.com/nevermined-io/cli/pull/75
