### ISSUE TITLE
Upload file to IPFS needs env vars not documentd

### ISSUE THREAD

**Issue by ialberquilla** [nevermined-io/cli#72]
## Describe the bug

In order to run `ncli utils upload` two env vars should be previously exported `IPFS_PROJECT_ID ` and `IPFS_PROJECT_SECRET ` with the infura values to connect to IPFS, but if this function is called without exporting these values get an error without noticing the user. 

The cli should notice the user that these vars are needed and should be exported. Also the docs should include it https://docs.nevermined.io/docs/cli/cli_commands/#upload-file

##  To Reproduce
1. run `ncli utils upload filename`

**Comment by aaitor** [comment]
The upload is done via `gateway` and these variables are not necessaries:

```
aitor@tijuana:~/Projects/Nevermined/cli(feature/v061)$ unset IPFS_PROJECT_ID 
aitor@tijuana:~/Projects/Nevermined/cli(feature/v061)$ unset IPFS_PROJECT_SECRET 
aitor@tijuana:~/Projects/Nevermined/cli(feature/v061)$ echo $IPFS_PROJECT_ID

aitor@tijuana:~/Projects/Nevermined/cli(feature/v061)$ echo IPFS_PROJECT_SECRET

aitor@tijuana:~/Projects/Nevermined/cli(feature/v061)$ yarn start  utils upload README.md 
yarn run v1.22.17
$ ts-node src/index.ts utils upload README.md
Uploading File to Filecoin ...
File uploaded to URL: cid://bafkreiaytnbubleonjpb5ht5xuqg7fj5swboytoqvbue44v6dhckf6n4k4
Password: 9pHvdjetC6p2LmBNBmI5czhbdP32yrbWHZeAsZIT2SY
Done in 10.24s.
```
